name: Telegram Notifications

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:

      # 🔹 PUSH
      - name: Notify Push
        if: github.event_name == 'push'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 New Commit
            
            👤 By: ${{ github.actor }}
            📝 Message: ${{ github.event.head_commit.message }}
            🌿 Branch: ${{ github.ref_name }}

            https://github.com/${{ github.repository }}/commit/${{ github.sha }}

      # 🔹 PR
      - name: Notify PR
        if: github.event_name == 'pull_request'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🔥 Pull Request
            
            👤 By: ${{ github.event.pull_request.user.login }}
            📌 Title: ${{ github.event.pull_request.title }}
            🧭 Action: ${{ github.event.action }}

            ${{ github.event.pull_request.html_url }}
